name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Verificar versão do Terraform
        run: terraform version

      - name: Inicializar Terraform
        run: terraform init

      - name: Validar Terraform
        run: terraform validate

      - name: Planejar infraestrutura
        run: terraform plan

      - name: Aplicar infraestrutura
        run: terraform apply -auto-approve